{% set name = "hstspreload" %}
{% set version = "2021.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5bb90f438bec40faf320170ee48cf1978f40423ee1ba39a57bb686f3f9c061c7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - hstspreload

about:
  home: https://hstspreload.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Chromium HSTS Preload list as a Python package and updated daily.
  doc_url: https://hstspreload.org/

extra:
  recipe-maintainers:
    - primozgodec
