{% set name = "hstspreload" %}
{% set version = "2020.9.23" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35822733ba67cfb4efc6cd7d1230b509f0bd42c90eeb329faf2fe679f801e40f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - hstspreload

about:
  home: https://hstspreload.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Chromium HSTS Preload list as a Python package and updated daily.
  doc_url: https://hstspreload.org/

extra:
  recipe-maintainers:
    - primozgodec
